const feedbackStrings = {
    "Criterion A": {
        
        "Above Average": "I am thoroughly impressed with your performance in our Individuals and Societies class. Your grasp of the key concepts and the depth of your understanding are commendable. You consistently demonstrate a strong ability to connect complex ideas, showing an impressive level of critical thinking.\n\nYour engagement with the course material goes beyond recalling factual information; you analyze and evaluate the information in a way that shows a deep understanding of the subject matter. Your ability to draw connections between various historical events, societal structures, and current affairs is particularly noteworthy.\n\nIn your written work and verbal contributions, you consistently articulate your ideas clearly and thoughtfully. Your arguments are well-structured and supported by relevant examples and evidence, which enhances the quality of your work.\n\nMoreover, your application of the learned concepts to real-world scenarios is exemplary. You not only understand the material but also apply it in a meaningful way, demonstrating insight and a mature perspective on global issues.\n\nYour active participation and insightful contributions greatly enrich our class discussions. I encourage you to continue challenging yourself and to seek out additional resources and perspectives, as this will further deepen your understanding and engagement with the subject.\n\nYou set a high standard in our class, and I am excited to see how you will continue to develop your skills and understanding in the field of Individuals and Societies. Keep up the excellent work and consider how you might use your knowledge and skills to make a positive impact in your community and beyond.\n\n",
        
        "Average": "You have shown a steady progression in our Individuals and Societies class, and I want to acknowledge your consistent efforts. Your grasp of the key concepts of our course is developing well, and you are beginning to make connections between the ideas we've discussed, which is encouraging.\n\nYou have demonstrated a basic understanding of the course material, and I've noticed that you can recall factual information and some of the main ideas. To deepen your understanding, I recommend that you try to engage more critically with the concepts. This can be done by asking 'why' or 'how' questions about the material, which will help you think more deeply about the subject matter.\n\nIn terms of applying these concepts, you are on the right track. I've seen instances in your work where you've applied what you've learned to different scenarios. To further enhance this skill, consider exploring more real-world examples and think about how the concepts we learn in class can be seen in everyday life. This approach can make the material more relevant and easier to understand.\n\nYour written and verbal responses show that you can communicate your ideas, but there's room for more detail and depth in your explanations. Try to expand on your answers by providing more examples, or by explaining the reasoning behind your thoughts.\n\nYour participation in class is valued, and I encourage you to continue contributing to discussions. Engaging more actively in class can also help reinforce your learning and understanding.\n\nOverall, you are making good progress. Remember, learning is an ongoing process, and with continued effort and a bit more depth in your engagement with the material, I am confident you will see further improvement.\n\n",
        
        "Below Average": "I appreciate the efforts you've put into our Individuals and Societies class. I've noticed your engagement with the course material, and I want to help you build on this foundation to enhance your understanding further.\n\nIn terms of grasping the key concepts, I see that you are beginning to understand some of the basic ideas. To deepen your comprehension, I suggest revisiting the main points from our lessons and class discussions. Don't hesitate to ask questions or seek clarification, either during class or in one-on-one sessions. Remember, questions are a great way to learn!\n\nYou've shown some understanding of the connections between different ideas and events, which is commendable. To strengthen this skill, try to think about how these concepts might relate to your own experiences or current events. This can make the material more relatable and easier to understand.\n\nWhen it comes to applying the concepts we learn, I encourage you to try more practice exercises or real-life examples. This can help in solidifying your understanding and making the concepts more tangible.\n\nAlso, I've noticed in your assessments that you sometimes struggle to express your ideas clearly. Take your time to organize your thoughts before writing, and consider creating a simple outline to guide your responses. This will help in making your answers more coherent and focused.\n\nYour participation in class discussions is valued, and I encourage you to continue sharing your thoughts. Every contribution is a step towards better understanding.\n\nRemember, learning is a journey, and it's okay to find some areas challenging. I am here to support you and guide you through this process. Keep persevering, and I am confident that you will see improvement in your understanding of the course material.\n\n"
    },
    
    
    "Criterion B": {
        
        "Above Average": "I am impressed with your performance in our recent units, particularly in the realm of investigation. Your ability to define and articulate research questions is notable for its clarity and focus, demonstrating a deep understanding of the topics we have explored. Your approach to collecting information is thorough and well-considered, showcasing your ability to discern and utilize relevant and reliable sources effectively.\n\nYour organizational skills are exemplary; you demonstrate a keen ability to synthesize and organize information in a way that is both logical and effective for your audience. This skill is further highlighted in the way you interpret data, where you not only draw insightful connections but also critically analyze the implications of your findings, adding depth to your work.\n\nThe presentation of your research findings is consistently strong. You exhibit a clear, coherent, and engaging style, effectively integrating various formats and perspectives to enhance the overall impact of your presentations. This not only demonstrates your understanding of the subject matter but also your skill in communicating complex ideas in an accessible manner.\n\nYour work consistently exceeds expectations, reflecting a high level of engagement and understanding in the field of I&S. I encourage you to continue challenging yourself and to consider how you might use your skills to contribute to broader discussions and applications in our future studies.\n\nKeep up the outstanding work, and I look forward to seeing how you will further apply and develop these skills in our upcoming units.\n\n",
        
        "Average": "You have made a commendable effort in developing your investigative skills in our recent units. Your ability to define the research question shows a growing understanding of the topics we have covered, though there's room to make your questions more focused and specific. I've noticed that you collect relevant information, but sometimes you may benefit from evaluating your sources more critically to ensure their reliability.\n\nYour organizational skills are developing; however, more consistent attention to how you organize your data and information could enhance the clarity of your findings. In interpreting information, you're beginning to draw connections and make inferences, which is a positive step. I encourage you to delve deeper into analyzing the implications of the data you gather.\n\nYour presentation of research findings is clear and demonstrates a fair understanding of the topic. To further improve, try to integrate more varied formats or perspectives in your presentations, which will help in conveying your ideas more compellingly.\n\nKeep up the hard work, and I am confident that with consistent effort, you will continue to grow and excel in your investigative skills.\n\n",
        
        "Below Average": "I've noticed your efforts in our recent I&S units and want to acknowledge the progress you've made, as well as offer some guidance to help you grow further. In defining research questions, I see that you're starting to grasp the topics we're studying. To enhance your understanding, try to think more critically about what you want to learn from each assignment, and don't hesitate to ask questions if you're unsure.\n\nWhen collecting information, you're gathering some relevant data, which is a good start. I encourage you to explore a wider range of sources and consider their reliability more carefully. This will not only improve the quality of your information but also deepen your understanding of the topic.\n\nIn terms of organizing your information, I suggest developing a more structured approach. Simple methods like creating outlines or categorizing your notes can make a big difference in how you process and understand the information you find.\n\nInterpreting data and findings is a skill that develops with practice. Try to look for patterns and connections in the information you gather. Remember, it's okay to make mistakes in this process – it's all part of learning.\n\nI've noticed that you can communicate your ideas during presentations, which is a positive aspect of your work. To make your presentations even more effective, consider how you might clearly express your main points and back them up with the information you've gathered.\n\nI believe in your potential and am here to support you in developing your investigative skills. Remember, improvement takes time and practice, so be patient with yourself and keep up your efforts.\n\n"
    },
    
    
    "Criterion C": {
        
        "Above Average": "I am truly impressed with your communication skills as demonstrated in our recent Individuals and Societies assessments. Your ability to articulate your ideas both in writing and oral discussions is commendable and stands out as a strength in your work.\n\nYou consistently present information in a structured and logical manner, making your arguments and explanations clear and easy to follow. This clarity of expression greatly enhances the effectiveness of your communication. Moreover, your use of subject-specific terminology is not only accurate but also aptly chosen, adding depth and precision to your discussions.\n\nWhat is particularly noteworthy is your ability to adapt your communication style to different formats and contexts. Whether it's written essays, presentations, or class discussions, you display a versatility that is exemplary. You engage your audience with a style that is both informative and engaging, which is a key skill in effective communication.\n\nYour visual and multimedia presentations show a high level of proficiency. The way you integrate text, images, and other media is both creative and effective, demonstrating an understanding of how different elements can come together to strengthen a message.\n\nI encourage you to continue honing these skills, as they will serve you well in all areas of your academic and future professional life. Perhaps you could challenge yourself further by exploring more diverse perspectives in your work or experimenting with new and innovative forms of communication.\n\nKeep up the excellent work. Your ability to communicate your ideas so effectively is a significant asset, and I look forward to seeing how you continue to develop this talent.\n\n",
        
        "Average": "I appreciate your efforts in our Individuals and Societies class, particularly in the area of communication. You have shown a good understanding of how to structure your ideas and present them in a coherent manner, which is commendable.\n\nIn your written work, you effectively communicate the main points and use relevant terminology, which shows your growing grasp of the subject. To enhance your writing, I encourage you to focus on developing more detailed explanations and incorporating a wider range of examples to support your arguments. This will add depth to your essays and reports.\n\nWhen it comes to oral presentations and discussions, you participate and share your ideas, which is great to see. To further improve, try to speak more confidently and consider varying your tone and pace to engage your audience more effectively. Practice will make this easier, and I am here to support you in this.\n\nYour use of visual aids and multimedia in presentations is a positive aspect of your work. To take this further, you could experiment with different types of visual representations or technology to make your presentations more impactful.\n\nRemember, effective communication is not just about delivering information; it's also about engaging your audience and conveying your ideas clearly. I encourage you to continue practicing these skills, both in written and spoken forms. With consistent effort and attention to detail, I am confident that you will see improvement in your communication skills.\n\nKeep up the good work, and don't hesitate to reach out if you need guidance or support in developing your communication skills.\n\n",
        
        "Below Average": "I've been observing your progress in our Individuals and Societies class and want to acknowledge the efforts you are making in developing your communication skills. Communication is a key skill, and like any skill, it improves with practice and dedication.\n\nIn your written work, I see that you are able to convey basic ideas related to our course material. To enhance your writing, I recommend focusing on organizing your thoughts more clearly. A simple outline before you start writing can help structure your essays and reports. Also, try to include specific examples or details from our lessons to support your points, as this will make your writing more effective and informative.\n\nDuring presentations and class discussions, I notice that you contribute, which is a good start. To improve your oral communication, consider practicing your speaking skills in a comfortable setting, perhaps with friends or family, or even in front of a mirror. This practice can build your confidence, which is an important aspect of effective communication.\n\nI also encourage you to engage more with various types of media and visual aids in your presentations. This not only makes your presentations more interesting but can also help in conveying your message more effectively. If you're unsure about how to do this, feel free to ask for help or ideas.\n\nRemember, the ability to communicate well is something that will benefit you in many areas of life. I am here to support and guide you in this learning process. Don't hesitate to reach out if you need extra help or resources.\n\nKeep persevering. With continued effort and practice, I am confident that you will see improvement in your communication skills.\n\n"
    },
    
    
    "Criterion D": {
        "Above Average": "I am truly impressed with your performance in the area of critical thinking in our Individuals and Societies class. Your ability to analyze complex information and draw insightful conclusions is remarkable and demonstrates a high level of understanding.\n\nYour analytical skills are a standout aspect of your work. You consistently delve into the deeper meanings of the topics we cover, examining various perspectives and implications. This depth of analysis is indicative of a mature and thoughtful approach to learning.\n\nIn evaluating different sources and perspectives, you demonstrate a keen understanding of the importance of considering different viewpoints and the context of information. Your ability to identify biases and question underlying assumptions in the material we study is exemplary. This critical examination is crucial for a well-rounded understanding of any subject.\n\nI am particularly impressed by the way you draw well-reasoned conclusions and make informed judgments based on evidence. Your arguments are consistently supported by detailed and relevant examples, which enhances the credibility and effectiveness of your viewpoints.\n\nYour contributions to class discussions are insightful and add significant value to our learning environment. You have a talent for stimulating deeper thought and discussion among your peers, which is a testament to your strong critical thinking skills.\n\nMoving forward, I encourage you to continue challenging yourself. Perhaps you could explore more interdisciplinary connections or take the initiative to research beyond the curriculum. This will not only deepen your own understanding but could also provide new perspectives to our class discussions.\n\nKeep up the excellent work. Your critical thinking abilities are a significant strength, and I look forward to seeing how you continue to develop and apply these skills in more complex and varied contexts.",
        
        "Average": "You have made steady progress in our Individuals and Societies class, especially in the area of critical thinking. Your engagement with our class material and your efforts to understand and analyze various perspectives are commendable.\n\nYou demonstrate a growing ability to analyze information, which is evident in your classwork and assignments. To enhance this skill, I encourage you to delve deeper into the 'why' and 'how' aspects of the topics we discuss. This deeper analysis will not only improve your critical thinking but also your overall understanding of the subject matter.\n\nIn evaluating different perspectives and sources, you show an initial understanding of the importance of considering various viewpoints. Moving forward, try to more thoroughly assess the reliability and bias of the information you come across. This will help you develop a more nuanced and critical perspective.\n\nWhen it comes to drawing conclusions and making judgments, you are starting to use evidence to support your views, which is a positive step. To further improve, aim to consistently back up your opinions with more detailed examples and evidence from a range of sources. This practice will strengthen your arguments and enhance your critical thinking abilities.\n\nI've noticed your contributions to class discussions, and I encourage you to continue participating. Sharing your ideas and listening to others can provide new insights and help you refine your own thoughts. Don't hesitate to ask questions or seek clarification when needed, as this is an important part of the learning process.\n\nOverall, you are on the right track with your critical thinking skills. With continued effort and a focus on deeper analysis and evaluation, I am confident that you will see further improvement.\n\nKeep up the good work, and remember that I am here to support you in your journey of learning and growth.",
        
        "Below Average": "I've been closely following your progress in our Individuals and Societies class and have noticed your hard work and dedication. I understand that critical thinking can be challenging, and I want to offer some guidance to help you develop these important skills.\n\nIn our recent units, you've shown an initial understanding of how to analyze information and make basic connections between ideas. To build on this, I encourage you to practice asking deeper questions about the material we cover in class. Try to think about the 'why' and 'how' behind the facts and concepts we discuss. This kind of questioning can help deepen your understanding and improve your analytical skills.\n\nWhen it comes to evaluating different perspectives and sources, I suggest spending more time considering the reliability and relevance of the information you encounter. Ask yourself questions about the author's purpose and the context of the source. This will help you develop a more critical eye when assessing information.\n\nYour ability to draw conclusions and make judgments based on evidence is a skill that will grow with practice. Start by trying to support your opinions with specific examples or evidence from our lessons or your readings. This practice will help strengthen your arguments and improve your critical thinking.\n\nI've noticed that when we discuss complex issues in class, you sometimes hold back. Remember, it's okay to share your thoughts, even if you're not sure. Class discussions are a great opportunity to explore ideas and learn from each other. Your perspective is valuable, and I encourage you to participate more actively.\n\nRemember, critical thinking is a skill that develops over time, and everyone progresses at their own pace. I am here to support you every step of the way. Please feel free to come to me if you need extra help, resources, or just someone to discuss your ideas with.\n\nKeep working hard, with your continued effort and willingness to challenge yourself, I am confident that you will make great strides in your critical thinking abilities."
    }
}; 

window.onload = function() {
    let gradesForm = document.getElementById("grades-form");
    let title = document.getElementById("title");

    gradesForm.addEventListener("submit", function(event){
        event.preventDefault();
        let gradesInput = document.getElementById("grades").value;
        let grades = [...gradesInput].map(function(grade) {
            return parseInt(grade, 10);
        });
        let feedback = generateCustomFeedback(grades);

        document.getElementById("feedback-area").innerText = feedback;
        gradesForm.style.display = 'none';
        title.style.display = 'none';
    });


    function generateCustomFeedback(grades) {
        let feedback = "";
        let criteria = ["Criterion A", "Criterion B", "Criterion C", "Criterion D"];

        for (let i = 0; i < grades.length; i++) {
            if (i < criteria.length) {
                let grade = grades[i];
                let category = categorizeGrade(grade);
                if (category === "Invalid Grade") {
                    return "Invalid grade entered. Please enter grades between 0 and 8.";
                }
                let criterionFeedback = feedbackStrings[criteria[i]][category];
                feedback += `${criteria[i]}: ${criterionFeedback}\n`;
            }
        }

        return feedback;
    }

    function categorizeGrade(grade) {
        if (grade >= 0 && grade <= 3) {
            return "Below Average";
        } else if (grade >= 4 && grade <= 5) {
            return "Average";
        } else if (grade >= 6 && grade <= 8) {
            return "Above Average";
        } else {
            return "Invalid Grade";
        }
    }
};


